"""컬럼 표시 스펙 (영문 컬럼명 → 한국어명 + 단위유형).

src/ui/shared/format.py 에서 분리 (모듈화 3단계, COL_SPEC 데이터 전용).
"""
from __future__ import annotations

# 컬럼 영문명 → (한국어명, 단위유형)
# 단위유형:
#   "ueok"    : 만원 -> 억원 변환, 소수점 2자리
#   "man"     : 만원 단위, 콤마
#   "ppyeong" : 만원/평 단위, 콤마
#   "area"    : 면적 m²
#   "pct"     : 퍼센트
#   "cnt"     : 거래건수 (콤마 int)
#   "year"    : 연도 (콤마 없음)
#   "raw_int" : 정수, 콤마
#   "txt"     : 문자
COL_SPEC = {
    "naver_url":        ("📲 네이버", "link"),
    "rank":             ("추천순위", "raw_int"),
    "ym":               ("년월", "txt"),
    "deals":            ("거래건수", "cnt"),
    "avg_price":        ("평균매매가", "ueok"),
    "median_price":     ("중위매매가", "ueok"),
    "min_price":        ("최저매매가", "ueok"),
    "max_price":        ("최고매매가", "ueok"),
    "avg_ppp":          ("평당가", "ppyeong"),
    "avg_area_m2":      ("평균전용면적", "area"),
    "avg_price_yoy_%":  ("매매가 전년대비", "pct"),
    "avg_ppp_yoy_%":    ("평당가 전년대비", "pct"),
    "apt_name":         ("단지명", "txt"),
    "build_year":       ("준공연도", "year"),
    "area_bucket":      ("전용면적", "area"),
    "trade_median":     ("매매중위가", "ueok"),
    "trade_count":      ("매매거래수", "cnt"),
    "rent_median":      ("전세환산중위가", "ueok"),
    "rent_count":       ("전월세거래수", "cnt"),
    "gap":              ("갭(매매-전세)", "ueok"),
    "gap_ratio_%":      ("갭비율", "pct"),
    "deposit_median":   ("보증금중위", "ueok"),
    "monthly_median":   ("월세중위", "man"),
    "invest":           ("실투자금", "ueok"),
    "annual_yield_%":   ("연수익률", "pct"),
    "recent_ppp":       ("최근평당가", "ppyeong"),
    "recent_deals":     ("최근거래수", "cnt"),
    "prior_ppp":        ("이전평당가", "ppyeong"),
    "prior_deals":      ("이전거래수", "cnt"),
    "change_%":         ("변동률", "pct"),
    "region":           ("지역", "txt"),
    "opportunities":    ("추천매물수", "cnt"),
    "unique_apts":      ("추천단지수", "cnt"),
    "avg_score":        ("평균점수", "pct"),
    "best_score":       ("최고점수", "pct"),
    "avg_prestige":     ("평균 대장점수", "pct"),
    "n_buyable":        ("매수가능매물수", "cnt"),
    "n_apts":           ("단지수", "cnt"),
    "score":            ("종합점수", "pct"),
    "jeonse_ratio":     ("전세가율", "pct"),
    "value_ratio":      ("저평가비율", "pct"),
    "activity":         ("거래활성도", "cnt"),
    "ppp_median":       ("평당가중위", "ppyeong"),
    "region_median_ppp":("지역평균평당가", "ppyeong"),
    "best_yield_%":     ("최고수익률", "pct"),
    "min_gap":          ("최저갭", "ueok"),
    "min_trade":        ("최저매매가", "ueok"),
    "ltv_%":            ("LTV", "pct"),
    "zone":             ("규제구분", "txt"),
    "loan_capacity":    ("대출가능액", "ueok"),
    "required_equity":  ("필요자기자본", "ueok"),
    "max_buy_price":    ("최대매수가", "ueok"),
    "affordable":       ("매수가능", "txt"),
    "price_growth_%":   ("평당가상승률(분석기간½)", "pct"),
    "leverage":         ("레버리지(배)", "pct"),
    "expected_roi_%":   ("예상자기자본수익률(분석기간½·비연환산)", "pct"),
    "expected_gain":    ("예상평가차익(억·비연환산)", "ueok"),
    "seed_usage_%":     ("시드활용도", "pct"),
    "best_roi_%":       ("최고예상수익률", "pct"),
    "avg_growth_%":     ("평균상승률", "pct"),
    "catalyst_score":   ("호재종합점수", "pct"),
    "manual_catalyst":  ("호재점수(수동)", "pct"),
    "tier_score":       ("상급지등급점수", "pct"),
    "tier_label":       ("급지", "txt"),
    "vol_score":        ("거래량점수", "pct"),
    "new_build_score":  ("신축점수", "pct"),
    "volume_momentum":  ("거래량모멘텀(배)", "pct"),
    "catalysts":        ("등록호재", "txt"),
    "catalyst_text":    ("등록호재", "txt"),
    "sentiment_score":  ("매수심리점수", "pct"),
    "accel_score":      ("가격가속도점수", "pct"),
    "skew_score":       ("고가매수점수", "pct"),
    "price_acceleration_%": ("가격가속도", "pct"),
    "mean_median_skew_%":   ("평균-중위격차", "pct"),
    "avg_sentiment":    ("평균매수심리", "pct"),
    "avg_volume_momentum": ("평균거래량모멘텀(배)", "pct"),
    "avg_accel":        ("평균가격가속도", "pct"),
    "avg_skew":         ("평균고가매수격차", "pct"),
    "n_complexes":      ("단지수", "cnt"),
    "location_score":   ("입지점수(카카오)", "pct"),
    "n_subway":         ("주변지하철", "cnt"),
    "n_school":         ("주변학교", "cnt"),
    "n_mart":           ("주변마트", "cnt"),
    "n_hospital":       ("주변병원", "cnt"),
    "supply_pressure":  ("공급압박지수", "pct"),
    "supply_units":     ("입주물량(호)", "raw_int"),
    "rs_score":            ("단지상대강도점수", "pct"),
    "jeonse_accel_score":  ("전세가율가속도점수", "pct"),
    "jeonse_accel_%p":     ("전세가율가속도(%p)", "pct"),
    "jeonse_quality_score": ("전세가율적정점수", "pct"),
    "jeonse_risk":          ("역전세리스크", "txt"),
    "leverage_mult":        ("갭레버리지(배)", "pct"),
    "supply_pressure_score": ("입주물량점수(역)", "pct"),
    "supply_units_12mo":   ("12개월입주물량(호)", "raw_int"),
    "population_score":    ("인구순유입점수", "pct"),
    "net_inflow_12mo":     ("12개월순유입(명)", "raw_int"),
    # 적정가 분석
    "jeonse_median":    ("전세환산중위가", "ueok"),
    "fair_value":       ("적정가(역산)", "ueok"),
    "fv_premium_%":     ("현재가-적정가(%)", "pct"),
    "verdict":          ("판정", "txt"),
    "annual_rent":      ("연간임대수입", "man"),
    "monthly_median":   ("월세중위", "man"),
    "avg_ppp":          ("평균평당가", "ppyeong"),
    "ma_ppp":           ("이동평균평당가", "ppyeong"),
    "overshoot_%":      ("이동평균대비(%)", "pct"),
    "recent_ppp":       ("최근평당가(단지)", "ppyeong"),
    "total_deals":      ("총거래수", "cnt"),
    # raw trade columns (단지 검색 시)
    "region_code":      ("지역코드", "txt"),
    "deal_date":        ("거래일", "txt"),
    "dong":             ("법정동", "txt"),
    "jibun":            ("지번", "txt"),
    "road_name":        ("도로명", "txt"),
    "area_m2":          ("전용면적", "area"),
    "floor":            ("층", "raw_int"),
    "deal_amount":      ("실거래가", "ueok"),
    "price_per_pyeong": ("평당가", "ppyeong"),
    "deal_year":        ("년", "year"),
    "deal_month":       ("월", "raw_int"),
    "deal_day":         ("일", "raw_int"),
}

